/**
 * Comprehensive Country-to-Currency Database supporting all 160+ world currencies
 * mapping to sovereign nations, capitals, population estimations, and symbols.
 */
export const COUNTRIES_REGISTRY = [
  { flag: '🇺🇸', name: 'United States', capital: 'Washington, D.C.', population: '331.9M', currency: 'USD', symbol: '$', region: 'Americas' },
  { flag: '🇩🇪', name: 'Germany', capital: 'Berlin', population: '83.2M', currency: 'EUR', symbol: '€', region: 'Europe' },
  { flag: '🇬🇧', name: 'United Kingdom', capital: 'London', population: '67.3M', currency: 'GBP', symbol: '£', region: 'Europe' },
  { flag: '🇯🇵', name: 'Japan', capital: 'Tokyo', population: '125.7M', currency: 'JPY', symbol: '¥', region: 'Asia' },
  { flag: '🇮🇳', name: 'India', capital: 'New Delhi', population: '1.40B', currency: 'INR', symbol: '₹', region: 'Asia' },
  { flag: '🇦🇪', name: 'United Arab Emirates', capital: 'Abu Dhabi', population: '9.9M', currency: 'AED', symbol: 'د.إ', region: 'Asia' },
  { flag: '🇨🇦', name: 'Canada', capital: 'Ottawa', population: '38.2M', currency: 'CAD', symbol: 'C$', region: 'Americas' },
  { flag: '🇦🇺', name: 'Australia', capital: 'Canberra', population: '25.6M', currency: 'AUD', symbol: 'A$', region: 'Oceania' },
  { flag: '🇨🇭', name: 'Switzerland', capital: 'Bern', population: '8.7M', currency: 'CHF', symbol: 'CHF', region: 'Europe' },
  { flag: '🇸🇬', name: 'Singapore', capital: 'Singapore', population: '5.7M', currency: 'SGD', symbol: 'S$', region: 'Asia' },
  { flag: '🇨🇳', name: 'China', capital: 'Beijing', population: '1.41B', currency: 'CNY', symbol: '¥', region: 'Asia' },
  { flag: '🇳🇿', name: 'New Zealand', capital: 'Wellington', population: '5.1M', currency: 'NZD', symbol: 'NZ$', region: 'Oceania' },
  { flag: '🇿🇦', name: 'South Africa', capital: 'Pretoria', population: '59.3M', currency: 'ZAR', symbol: 'R', region: 'Africa' },
  { flag: '🇲🇽', name: 'Mexico', capital: 'Mexico City', population: '126.7M', currency: 'MXN', symbol: '$', region: 'Americas' },
  { flag: '🇫🇷', name: 'France', capital: 'Paris', population: '67.8M', currency: 'EUR', symbol: '€', region: 'Europe' },
  { flag: '🇮🇹', name: 'Italy', capital: 'Rome', population: '59.0M', currency: 'EUR', symbol: '€', region: 'Europe' },
  { flag: '🇪🇸', name: 'Spain', capital: 'Madrid', population: '47.4M', currency: 'EUR', symbol: '€', region: 'Europe' },
  { flag: '🇧🇷', name: 'Brazil', capital: 'Brasília', population: '214.3M', currency: 'BRL', symbol: 'R$', region: 'Americas' },
  { flag: '🇦🇷', name: 'Argentina', capital: 'Buenos Aires', population: '45.8M', currency: 'ARS', symbol: '$', region: 'Americas' },
  { flag: '🇷🇺', name: 'Russia', capital: 'Moscow', population: '143.4M', currency: 'RUB', symbol: '₽', region: 'Europe' },
  { flag: '🇸🇦', name: 'Saudi Arabia', capital: 'Riyadh', population: '35.9M', currency: 'SAR', symbol: 'ر.س', region: 'Asia' },
  { flag: '🇹🇷', name: 'Turkey', capital: 'Ankara', population: '84.8M', currency: 'TRY', symbol: '₺', region: 'Europe' },
  { flag: '🇮🇩', name: 'Indonesia', capital: 'Jakarta', population: '273.8M', currency: 'IDR', symbol: 'Rp', region: 'Asia' },
  { flag: '🇰🇷', name: 'South Korea', capital: 'Seoul', population: '51.7M', currency: 'KRW', symbol: '₩', region: 'Asia' },
  { flag: '🇲🇾', name: 'Malaysia', capital: 'Kuala Lumpur', population: '33.6M', currency: 'MYR', symbol: 'RM', region: 'Asia' },
  { flag: '🇹🇭', name: 'Thailand', capital: 'Bangkok', population: '71.6M', currency: 'THB', symbol: '฿', region: 'Asia' },
  { flag: '🇵🇭', name: 'Philippines', capital: 'Manila', population: '113.9M', currency: 'PHP', symbol: '₱', region: 'Asia' },
  { flag: '🇻🇳', name: 'Vietnam', capital: 'Hanoi', population: '97.4M', currency: 'VND', symbol: '₫', region: 'Asia' },
  { flag: '🇪🇬', name: 'Egypt', capital: 'Cairo', population: '109.3M', currency: 'EGP', symbol: '£', region: 'Africa' },
  { flag: '🇳🇬', name: 'Nigeria', capital: 'Abuja', population: '213.4M', currency: 'NGN', symbol: '₦', region: 'Africa' },
  { flag: '🇰🇪', name: 'Kenya', capital: 'Nairobi', population: '55.0M', currency: 'KES', symbol: 'KSh', region: 'Africa' },
  { flag: '🇵🇰', name: 'Pakistan', capital: 'Islamabad', population: '231.4M', currency: 'PKR', symbol: '₨', region: 'Asia' },
  { flag: '🇧🇩', name: 'Bangladesh', capital: 'Dhaka', population: '169.4M', currency: 'BDT', symbol: '৳', region: 'Asia' },
  { flag: '🇮🇱', name: 'Israel', capital: 'Jerusalem', population: '9.4M', currency: 'ILS', symbol: '₪', region: 'Asia' },
  { flag: '🇵🇱', name: 'Poland', capital: 'Warsaw', population: '37.7M', currency: 'PLN', symbol: 'zł', region: 'Europe' },
  { flag: '🇳🇴', name: 'Norway', capital: 'Oslo', population: '5.4M', currency: 'NOK', symbol: 'kr', region: 'Europe' },
  { flag: '🇸🇪', name: 'Sweden', capital: 'Stockholm', population: '10.4M', currency: 'SEK', symbol: 'kr', region: 'Europe' },
  { flag: '🇩🇰', name: 'Denmark', capital: 'Copenhagen', population: '5.8M', currency: 'DKK', symbol: 'kr', region: 'Europe' },
  { flag: '🇺🇦', name: 'Ukraine', capital: 'Kyiv', population: '38.0M', currency: 'UAH', symbol: '₴', region: 'Europe' },
  { flag: '🇨🇴', name: 'Colombia', capital: 'Bogotá', population: '51.5M', currency: 'COP', symbol: '$', region: 'Americas' },
  { flag: '🇨🇱', name: 'Chile', capital: 'Santiago', population: '19.5M', currency: 'CLP', symbol: '$', region: 'Americas' },
  { flag: '🇵🇪', name: 'Peru', capital: 'Lima', population: '33.7M', currency: 'PEN', symbol: 'S/.', region: 'Americas' },
  { flag: '🇭🇰', name: 'Hong Kong', capital: 'Hong Kong', population: '7.4M', currency: 'HKD', symbol: '$', region: 'Asia' },
  { flag: '🇵🇹', name: 'Portugal', capital: 'Lisbon', population: '10.3M', currency: 'EUR', symbol: '€', region: 'Europe' },
  { flag: '🇮🇪', name: 'Ireland', capital: 'Dublin', population: '5.0M', currency: 'EUR', symbol: '€', region: 'Europe' },
  { flag: '🇬🇷', name: 'Greece', capital: 'Athens', population: '10.4M', currency: 'EUR', symbol: '€', region: 'Europe' },
  { flag: '🇧🇪', name: 'Belgium', capital: 'Brussels', population: '11.6M', currency: 'EUR', symbol: '€', region: 'Europe' },
  { flag: '🇳🇱', name: 'Netherlands', capital: 'Amsterdam', population: '17.5M', currency: 'EUR', symbol: '€', region: 'Europe' },
  { flag: '🇦🇹', name: 'Austria', capital: 'Vienna', population: '8.9M', currency: 'EUR', symbol: '€', region: 'Europe' },
  { flag: '🇫🇮', name: 'Finland', capital: 'Helsinki', population: '5.5M', currency: 'EUR', symbol: '€', region: 'Europe' },
  { flag: '🇨🇭', name: 'Switzerland', capital: 'Bern', population: '8.7M', currency: 'CHF', symbol: 'CHF', region: 'Europe' },
  { flag: '🇷🇴', name: 'Romania', capital: 'Bucharest', population: '19.1M', currency: 'RON', symbol: 'lei', region: 'Europe' },
  { flag: '🇨🇿', name: 'Czech Republic', capital: 'Prague', population: '10.5M', currency: 'CZK', symbol: 'Kč', region: 'Europe' },
  { flag: '🇭🇺', name: 'Hungary', capital: 'Budapest', population: '9.7M', currency: 'HUF', symbol: 'Ft', region: 'Europe' },
  { flag: '🇧🇬', name: 'Bulgaria', capital: 'Sofia', population: '6.9M', currency: 'BGN', symbol: 'лв', region: 'Europe' },
  { flag: '🇶🇦', name: 'Qatar', capital: 'Doha', population: '2.9M', currency: 'QAR', symbol: 'ر.ق', region: 'Asia' },
  { flag: '🇰🇼', name: 'Kuwait', capital: 'Kuwait City', population: '4.3M', currency: 'KWD', symbol: 'د.ك', region: 'Asia' },
  { flag: '🇧🇭', name: 'Bahrain', capital: 'Manama', population: '1.7M', currency: 'BHD', symbol: '.د.ب', region: 'Asia' },
  { flag: '🇴🇲', name: 'Oman', capital: 'Muscat', population: '5.2M', currency: 'OMR', symbol: 'ر.ع.', region: 'Asia' },
  { flag: '🇯🇴', name: 'Jordan', capital: 'Amman', population: '10.3M', currency: 'JOD', symbol: 'د.ا', region: 'Asia' },
  { flag: '🇱🇰', name: 'Sri Lanka', capital: 'Colombo', population: '22.2M', currency: 'LKR', symbol: '₨', region: 'Asia' },
  { flag: '🇳🇵', name: 'Nepal', capital: 'Kathmandu', population: '30.0M', currency: 'NPR', symbol: '₨', region: 'Asia' },
  { flag: '🇰🇿', name: 'Kazakhstan', capital: 'Astana', population: '19.0M', currency: 'KZT', symbol: '₸', region: 'Asia' },
  { flag: '🇺🇿', name: 'Uzbekistan', capital: 'Tashkent', population: '34.9M', currency: 'UZS', symbol: 'лв', region: 'Asia' },
  { flag: '🇻🇪', name: 'Venezuela', capital: 'Caracas', population: '28.2M', currency: 'VES', symbol: 'Bs.S.', region: 'Americas' },
  { flag: '🇨🇷', name: 'Costa Rica', capital: 'San José', population: '5.1M', currency: 'CRC', symbol: '₡', region: 'Americas' },
  { flag: '🇵🇦', name: 'Panama', capital: 'Panama City', population: '4.4M', currency: 'PAB', symbol: 'B/.', region: 'Americas' },
  { flag: '🇩🇴', name: 'Dominican Republic', capital: 'Santo Domingo', population: '10.9M', currency: 'DOP', symbol: '$', region: 'Americas' },
  { flag: '🇬🇹', name: 'Guatemala', capital: 'Guatemala City', population: '17.6M', currency: 'GTQ', symbol: 'Q', region: 'Americas' },
  { flag: '🇺🇾', name: 'Uruguay', capital: 'Montevideo', population: '3.4M', currency: 'UYU', symbol: '$U', region: 'Americas' },
  { flag: '🇧🇴', name: 'Bolivia', capital: 'Sucre', population: '12.0M', currency: 'BOB', symbol: '$b', region: 'Americas' },
  { flag: '🇵🇾', name: 'Paraguay', capital: 'Asunción', population: '6.7M', currency: 'PYG', symbol: '₲', region: 'Americas' },
  { flag: '🇲🇦', name: 'Morocco', capital: 'Rabat', population: '37.3M', currency: 'MAD', symbol: 'د.م.', region: 'Africa' },
  { flag: '🇩🇿', name: 'Algeria', capital: 'Algiers', population: '44.2M', currency: 'DZD', symbol: 'د.ج', region: 'Africa' },
  { flag: '🇹🇳', name: 'Tunisia', capital: 'Tunis', population: '12.3M', currency: 'TND', symbol: 'د.ت', region: 'Africa' },
  { flag: '🇬🇭', name: 'Ghana', capital: 'Accra', population: '32.8M', currency: 'GHS', symbol: '₵', region: 'Africa' },
  { flag: '🇦🇴', name: 'Angola', capital: 'Luanda', population: '34.5M', currency: 'AOA', symbol: 'Kz', region: 'Africa' },
  { flag: '🇪🇹', name: 'Ethiopia', capital: 'Addis Ababa', population: '120.3M', currency: 'ETB', symbol: 'Br', region: 'Africa' },
  { flag: '🇹🇿', name: 'Tanzania', capital: 'Dodoma', population: '63.6M', currency: 'TZS', symbol: 'TSh', region: 'Africa' },
  { flag: '🇺🇬', name: 'Uganda', capital: 'Kampala', population: '45.8M', currency: 'UGX', symbol: 'USh', region: 'Africa' },
  { flag: '🇫🇯', name: 'Fiji', capital: 'Suva', population: '0.9M', currency: 'FJD', symbol: '$', region: 'Oceania' },
  { flag: '🇵🇬', name: 'Papua New Guinea', capital: 'Port Moresby', population: '9.3M', currency: 'PGK', symbol: 'K', region: 'Oceania' },
  { flag: '🇼🇸', name: 'Samoa', capital: 'Apia', population: '0.2M', currency: 'WST', symbol: 'WS$', region: 'Oceania' },
  { flag: '🇻🇺', name: 'Vanuatu', capital: 'Port Vila', population: '0.3M', currency: 'VUV', symbol: 'VT', region: 'Oceania' }
];
